@tool
class_name LatexSamples

const LATEX_SAMPLES: PackedStringArray = [
	"x + 1",
	"x + 2",
	"x + 3",
	"x + 4",
	"x + 5",
	"x - 1",
	"x - 2",
	"x - 3",
	"x - 4",
	"x - 5",
	"1x",
	"2x",
	"3x",
	"4x",
	"5x",
	"\\frac{1}{x}",
	"x^2",
	"\\sqrt{x}",
	"\\sin(x)",
	"\\cos(x)",
	"\\tan(x)",
	"e^{x}",
	"\\ln(x)",
	"\\frac{1}{e^{x}}",
	"e^{-x^2}",
	"\\frac{1}{x^2 + 1}",
	"\\frac{x}{x + 1}",
	"\\sqrt{1 - x^2}",
	"x^{x}",
	"\\sqrt[3]{x}",
	"\\tan^{-1}(x)",
	"\\frac{d}{dx} e^{x}",
	"\\frac{d}{dx} \\sin(x)",
	"\\int x^2 \\, dx",
	"\\int e^{-x^2} \\, dx",
	"\\int \\frac{1}{x} \\, dx",
	"\\lim_{x \\to 0} \\frac{\\sin x}{x}",
	"\\lim_{x \\to \\infty} \\frac{1}{x}",
	"\\sum_{n=0}^{\\infty} \\frac{x^n}{n!}",
	"\\sum_{n=1}^{\\infty} \\frac{1}{n^2}",
	"\\int_{0}^{x} e^{-t^2} \\, dt",
	"\\log_{10}(x)",
	"\\sqrt{x^2 + y^2}",
	"\\frac{1}{\\sqrt{2\\pi}} e^{-\\frac{x^2}{2}}",
	"e^{ix}",
	"\\sin(x^2)",
	"\\cos(\\pi x)",
	"\\frac{\\sin(x)}{x}",
	"\\sqrt{\\ln(x)}",
	"\\int_0^{\\pi} \\sin(x) \\, dx",
	"\\int_0^{1} t^x \\, dt",
	"\\lim_{x \\to 0} \\frac{e^x - 1}{x}",
	"\\frac{d}{dx} \\tan^{-1}(x)"
]


static func random() -> String:
	return LATEX_SAMPLES[randi_range(0, LATEX_SAMPLES.size() - 1)]
